//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblApplicationInfo
    {
        public long Id { get; set; }
        public string ApplicationName { get; set; }
        public string ApplicationDetails { get; set; }
        public string ContactUsDetails { get; set; }
    }
}
