//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOAuthDetail
    {
        public long Id { get; set; }
        public string FacebookAppId { get; set; }
        public string FacebookKey { get; set; }
        public string TwitterAppId { get; set; }
        public string TwitterKey { get; set; }
    }
}
