//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TblUserInfo
    {
        public long UserId { get; set; }
        [Required(ErrorMessage = "username is required")]
        [StringLength(15, ErrorMessage = "Maximum 15 characters required")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "password is required")]
        [StringLength(15, ErrorMessage = "Minimum 15 characters required")]
        public string Password { get; set; }
        [Required(ErrorMessage = "firstname is required")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "lastname is required")]
        public string LastName { get; set; }
        public Nullable<decimal> PhoneNumber { get; set; }
        public string City { get; set; }
        public string State { get; set; }
    }
}
